GermanZero-de/localzero-monitoring

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
This just does the basic integration. We will probably have to do some extra work once we start modelling.
> Add pyright

- .pre-commit-config.yaml
- cpmonitor/admin.py
- cpmonitor/models.py
- cpmonitor/urls.py
Also disabled pre-commit pyright sadly as it doesn't use the right venv and the incantation didn't work.
> A example sector model integrated into the admin. 

- README.md
- cpmonitor/admin.py
- cpmonitor/models.py
Ohne migrations, da wir alle noch auf leerer Datenbank anfangen.
> Model für Data + Lookup angelegt.

- cpmonitor/admin.py
- cpmonitor/models.py
Added default values to model
minor customizing of admin site
> minor customizing of admin site

- cpmonitor/admin.py
- cpmonitor/models.py
@Holger-GZ Let me know if I can merge this or if it would interfere with your activity.
> Model: City, recursive Task.

- README.md
- I was irritated by the build number thing ... drop it if you think it's not helpful
- Removed a few additional ""
> Tiny readme additions

- .vscode/extensions.json
- config/settings/base.py
- cpmonitor/admin.py
- cpmonitor/models.py
- cpmonitor/views.py
- poetry.lock
- pyproject.toml
> Tree structure or Alternatives.

- .dockerignore
- Dockerfile
- README.md
- config/settings/container.py
- docker-compose.yml
- poetry.lock
- pyproject.toml
> Add frontend build to container

- Dockerfile
- config/nginx/nginx.conf
- config/settings/base.py
- docker-compose.yml
@fblampe and I spend a lot of today trying to figure out how to get 
http://monitoring-test.localzero.net/
to work.
We are now almost there (index page works, admin page appears but login fails).
This contains a small amount of quick fixes needed to get things to work.  
@fblampe has a TODO list with next steps.  Then we will try again.
> Fixes for deployment

- .env.local
- .env.production
- Dockerfile
- docker-compose.yml
> Ship nginx config with django container and mount it into nginx container

- Dockerfile
- README.md
> Add manage.py to container for DB management

- cpmonitor/templates/index.html
> Add footer with admin login

- README.md
- config/nginx/nginx.conf
- cpmonitor/static/robots.txt
> Add robots.txt (and update README)

- .github/workflows/ci.yml
- README.md
- docker-compose.yml
- pyproject.toml
> 20 GitHub actions

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- cpmonitor/templates/admin/task_changelist.html
- cpmonitor/templates/base.html
- cpmonitor/templates/city.html
- cpmonitor/templates/index.html
- cpmonitor/templates/task.html
- pyproject.toml
Closes #92.
In addition, the pre-commit hooks are now also called during CI. This will remind people without the hook enabled in their repo.
> Add pre-commit hook and CI test to verify model changes match migrations

- README.md
- config/nginx/htpasswd
- config/nginx/nginx.conf
- e2e_tests/conftest.py
> Simple password protection. #94

- README.md
> Doc how to skip commit hooks.

- cpmonitor/templates/city.html
- cpmonitor/templates/group.html
- cpmonitor/templates/index.html
- cpmonitor/templates/pageframe.html
- cpmonitor/templates/task.html
- cpmonitor/views.py
- e2e_tests/database/test_database.json
- e2e_tests/test_city_page.py
- e2e_tests/test_task_page.py
added tabler layout for task page and task group page
only first and second level of the tree are working properly, arbitrary nesting does not work yet, because the slugs field in the database contains incorrect data, slug generation/updating might be broken
Closes #113
> 61 frontend

- cpmonitor/admin.py
Closes #52.
Found this solution when doing research for #124.
> [#52] Filter choices for ref node for move by city.

- cpmonitor/models.py
- cpmonitor/static/css/main.css
- cpmonitor/static/css/main.css.map
- cpmonitor/static/css/main.scss
- cpmonitor/templates/base.html
- cpmonitor/templates/city.html
- cpmonitor/templates/group.html
- cpmonitor/templates/pageframe.html
- cpmonitor/templates/task.html
- cpmonitor/views.py
- e2e_tests/database/test_database.json
closes #125
- adds some more date on the tasks page
- adds breadcrumbs
- fixes link of page title, links to city homepage, now
- show overall status across all tasks on city homepage
> next iteration for tasks page, breadcrumbs, overall status

- README.md
- e2e_tests/database/test_database.json
> 161 pytest bug

- .dockerignore
- .gitignore
- README.md
Just some minor bits I tripped over today..
> Clean up docs and docker context

- poetry.lock
- pyproject.toml
the djlint project fixed the issue reported in #170 very quickly. This is an update to the lastest version which then closes #170
> [#170] update djlint to fixed version

- README.md
- docker/reverseproxy/.env.server
- docker/reverseproxy/conf.d/nginx.conf
> 137 separate production and test server

- config/nginx/extras-production/extras.conf
> [#218] Serve robots.txt in production

- config/nginx/extras-production/extras.conf
- config/nginx/extras-production/htpasswd
removes basic auth from prod once it is deployed
> 215 remove basic auth from prod

- README.md
(this does not include #227 since that's a bit more difficult)
> Document deployment of reverse proxy settings

- cpmonitor/static/css/main.css
- cpmonitor/static/css/main.scss
- cpmonitor/templates/administration_checklist.html
- cpmonitor/templates/cap_checklist.html
- e2e_tests/test_administration_checklist_page.py
- e2e_tests/test_cap_checklist_page.py
> [#254] replace red crossed circle by an empty circle

- cpmonitor/templates/city.html
- cpmonitor/views.py
- e2e_tests/database/test_database.json
- e2e_tests/test_city_page.py
Change date format to show years if there is more than 365 days.
Closes #291.
> change date format to show years

- README.md
> [#245] Document Apple silicon workaround

- e2e_tests/test_mobile.py
Closes #277 
Tests if the burger is there and if menu and its submenu does open.
> Test for the burger menu in mobile mode

- .env
- .env.production
- .env.testing
- .github/workflows/backup.yml
- README.md
- backup.sh
- crontab
- deploy.sh
- docker-compose.yml
- docker/cpmonitor/Dockerfile
> [#135] regularly backup the database and media files

- .github/workflows/backup.yml
- README.md
- backup.sh
- deploy.sh
- start-testing-with-prod-data.sh
> [#227] Script for running the testing app with prod data

- cpmonitor/admin.py
- cpmonitor/models.py
@cafischer Da waren schon viele ganz ordentliche Kommentare. Kannst Du bitte insgesamt über die Dateien `models.py`, `admin.py`, and `utils.py` schauen, ob da Alles verständlich ist?
> [#299] document models.py and admin.py.

- cpmonitor/templates/base.html
awaiting @timbuktutimbuktu 's opinion...
> Improve wording of 'in development' banner

- cpmonitor/views.py
- e2e_tests/database/test_database.json
- e2e_tests/test_task_page.py
> Fix for bad PR #309

- cpmonitor/templates/snippets/taskcard.html
- cpmonitor/templatetags/filters.py
> [#362] add icons and tooltips on executation status ribbons

- e2e_tests/test_admin.py
> [#405] test new cap edit page

- config/settings/base.py
- cpmonitor/admin.py
- cpmonitor/apps.py
- cpmonitor/templates/admin/index.html
- cpmonitor/urls.py
> 389 html martor

- frontend/app/components/Header.tsx
- frontend/app/globals.scss
- frontend/app/layout.tsx
- frontend/app/page.module.scss
- frontend/app/page.tsx
> 448 dashboard page layout

- cpmonitor/serializers.py
- frontend/app/CityService.tsx
- frontend/app/[city]/kap_checkliste/page.tsx
- frontend/app/[city]/page.tsx
- frontend/app/common.scss
- frontend/app/components/ChecklistItem.tsx
- frontend/app/components/LocalGroup.tsx
- frontend/app/components/styles/CapChecklistItem.module.scss
- frontend/app/globals.scss
- frontend/app/page.tsx
- frontend/app/projektbeschreibung/page.tsx
- frontend/package-lock.json
- frontend/package.json
closes #457 
Findet man unter der url: http://localhost:3000/beispielstadt/kap_checkliste
> 457 checklist cap

- frontend/app/components/ImplementationIndicator.tsx
- frontend/app/components/Tile.tsx
- frontend/app/components/styles/ImplementationIndicator.module.scss
- frontend/app/components/styles/Tile.module.scss
- frontend/app/page.tsx
closes #439 
Blauen Balken unten dran machen darf gern wer anderes :sweat_smile:
> 439 thermometer

- frontend/app/CityHooks.ts
- frontend/app/[city]/kap_checkliste/page.tsx
- frontend/app/[city]/massnahmen/[...task]/page.tsx
- frontend/app/[city]/massnahmen/page.tsx
- frontend/app/[city]/page.tsx
- frontend/app/[city]/verwaltungsstrukturen_checkliste/page.tsx
- frontend/app/globals.scss
- frontend/app/page.tsx
- frontend/app/projektbeschreibung/page.tsx
> 470 project page

- cpmonitor/serializers.py
- frontend/app/CityHooks.ts
- frontend/app/[city]/page.tsx
- frontend/app/[city]/waermeplanung_checkliste/page.tsx
- frontend/app/components/ChecklistItem.tsx
- frontend/package-lock.json
- frontend/package.json
> 460 energy checklist

- frontend/app/[city]/massnahmen/page.tsx
> 455 tasks assessment

- frontend/app/page.tsx
> 444 text opener

- frontend/app/components/Header.tsx
- frontend/app/globals.scss
> [#532] suche aus navbar entfernen

- cpmonitor/serializers.py
- frontend/app/(dashboard)/[city]/page.module.scss
- frontend/app/(dashboard)/[city]/page.tsx
- frontend/types/index.d.ts
> [#612] fehlende Diagramme auf Stadtebene

- frontend/app/(dashboard)/[city]/page.module.scss
- frontend/app/(dashboard)/[city]/page.tsx
- frontend/app/components/ImageModal.tsx
> [#612] diagramm positionierung

- cpmonitor/admin.py
> [#626] site admins may edit users again.

- frontend/app/components/TaskSummary.tsx
> Server Fehler Augsburg

- cpmonitor/serializers.py
- cpmonitor/urls.py
- cpmonitor/views.py
Fixes #640
Endpunkt api/tasks/top wurde hinzugefügt. Tasks mit mit draft_mode:true werden rausgefiltert. City name und slug werden hinzugefügt.
> Rest Endpunkt für Top Maßnahmen

- frontend/next.config.mjs
- frontend/package-lock.json
- frontend/package.json
> Enable new frontend to be run using dev-server for easier local testing and debugging

- frontend/app/(pages)/start/page.tsx
- frontend/app/components/BreadCrumb.tsx
- frontend/app/components/TileList.tsx
- frontend/app/components/styles/Subheader.module.scss
- frontend/app/globals.scss
Some small visual improvements regarding readability and paddings (the title readability could probably be improved even more)
The heading sizes I decreased, because they take up quite much space atm and because the mockup had definitely smaller headings. However, I am open for comments / feedback / opinions :) 
| Before | Now |
|--------|--------|
| <img width="1385" alt="image" src="https://github.com/user-attachments/assets/9a60aa83-827f-4a8a-bb34-c3dd699e0bfb" /> | <img width="1371" alt="image" src="https://github.com/user-attachments/assets/7bd77325-9895-41ea-8f85-8d08d400558f" /> |
| <img width="1452" alt="image" src="https://github.com/user-attachments/assets/f8718498-1445-44cb-91f6-dc4724572e47" /> | <img width="1502" alt="image" …
> Fix small UI and accessibility improvements

- frontend/app/components/MeasureCardContent.tsx
- frontend/app/components/MeasuresAccordion.tsx
- frontend/app/globals.scss
- added a showReadMore boolean that determines if "Mehr lesen ..." is to be shown inside the measure card
- restyle the "Mehr lesen ..." cause it looked quite raw before
| Before | Now |
|--------|--------|
| <img width="838" height="507" alt="image" src="https://github.com/user-attachments/assets/f125891b-18fd-47e1-b47d-aa915f383c38" /> | <img width="856" height="700" alt="image" src="https://github.com/user-attachments/assets/6ff3438a-a631-4578-9236-0b1b387ea9ee" /> |
Fyi: I used the [GermanZero styling](https://germanzero.de/) of links as an inspiration
> 537 mehr lesen bzw eine seite dann und nur dann wenn lokalteams 
