config/settings/base.py
django-ordered-model was removed from dependencies (poetry) in commit 9596629, but forgotten to remove from INSTALLED_APPS thus causing a ModuleNotFoundError when starting up the server in a fresh installation
=> remove ordered_model from INSTALLED_APPS

.pre-commit-config.yaml, README.md, poetry.lock, pyproject.toml
Closes #80 
since I will need it to start working on frontend templates, I thought I'd quickly do this. Added the pre-commit hook. djlint does not only autoformat, but lint, too. Our curret templates show up with a couple of errors, but I think we can fix them as we go along.
=> #80 add djlint to autoformat django templates

.github/workflows/ci.yml
Fix for #92. Otherwise, merges to `main` will cause a failed CI run.
=> #92 skip no-commit-to-branch in CI.

.github/workflows/deploy.yml
This is only a small part of #21...
Apart from this PR I did some stuff here on GitHub:
- Added two [environments](https://github.com/GermanZero-de/klimaschutzmonitor/settings/environments).
- Added the needed SSH stuff in the repository [secrets](https://github.com/GermanZero-de/klimaschutzmonitor/settings/secrets/actions)
- Added an example variable `DEPLOY_TO_DIR` both as "[repository variable](https://github.com/GermanZero-de/klimaschutzmonitor/settings/variables/actions)" and as "environment variable". (The latter will overwrite the former.)
All this and also the extra job "Get Environment" in the workflow lead to this nice little thingy on the GitHub main page:
I tried my best  to achieve the following: I wanted to have a single job for both deployments to production and test. …
=> [#21] Prepare deploy workflow with ssh access to servers.

cpmonitor/views.py
A city filter was missing in views.tasks leading to an exception if two cities had a task with the same slug.
Also rewrote the filter in in _get_children to make it slightly easier to understand.
=> #61 fix missing city filter

.env.testing, README.md, config/nginx/conf.d/nginx.conf, crontab, docker-compose.yml, e2e_tests/conftest.py, pyproject.toml, renew-cert.sh
Part of #30 - adds a container that can do certificate renewal when triggered by a cron job (still to be documented and installed on the server).
I had to deploy this on the server to test, and it's working now for both testing and production with the same certificate. I used my own mail adress for notifications for now. The cert is valid for 60 days, until which we should have finished installing the cronjob.
=> #30 tls certs

cpmonitor/migrations/0022_chart_internal_information_city_internal_information_and_more.py
Django and GitHub bit each other joyfully in the arse... Due to the PR #231 sitting around too long, there was a conflict, which was not detected, since no changes on that PR triggered a CI run.
=> [#175] Updating migration to current state of main branch.

README.md, docker-compose.yml
Closes #236 .
Since I had to deploy this to the server to check if it works... it is already deployed to the server.
=> [#236] Fix deployments always affecting both environments

cpmonitor/static/js/main.js
closes #62
completes the last task of #62 and makes the tooltips accessible. They could always be accessed by simple touch. The problem was that the touch also triggered the link on the card and thus send the user to the subpage.
I added a line of javascript to prevent the default link behaviour. No you can touch/click the statusbar to see the tooltips and touch/click anywhere else on the card to get to the subpage
=> [#62] make statusbar tooltips accessible on touch devices

config/nginx/conf.d/nginx.conf, config/settings/container.py, cpmonitor/static/js/localzero.js, cpmonitor/templates/base.html, docker/reverseproxy/conf.d/nginx.conf
=> 255 security

cpmonitor/admin.py, cpmonitor/templates/invitations/messages/invite_for_logged_in_user.txt, cpmonitor/templates/invitations/messages/invite_for_logged_in_user_invalid.txt, cpmonitor/tests/permissions_test.py, cpmonitor/views.py
This is a fix of small holes in #23. I probably should have entered new issue(s). Sorry for my lazyness.
Solved:
- If a (non-super-)user is both editor and admin for a city, the appeared twice in some lists, which lead to failures of some views. After this PR that is fine, but the city still appears twice in the filter list. New issue: #282
- If a user is logged in and uses an invitation link, it is rejected. After this PR the access right connected to the invitation link is added to the user.
=> [#23] Existing users can use invitation link.

config/nginx/conf.d/nginx.conf
Workaround for #284 - remove CSP header again until we find a real fix so we can deploy and people can keep working.
=> [#284] Workaround: Remove content security policy for now

config/nginx/conf.d/nginx.conf
closes #284 
I also added an issue at Martor: https://github.com/agusmakmun/django-markdown-editor/issues/218
=> [#284] add content security header that works with martor

.dockerignore, .github/workflows/ci.yml, .github/workflows/deploy.yml, README.md, deploy.sh, docker/reverseproxy/docker-compose.yml
Part of #21 .
Adds a script that automatically performs all deployment steps currently documented in the README: it builds the app and container images, copies them, creates backups, stops old app version and starts the new one.
Copying over production data to testing is currently not documented and therefore not implemented.
I tested the deploy.yml workflow locally using [act](https://github.com/nektos/act) with some dummy values and it executed the deploy.sh script with the correct environment as argument. We have to see if the workflow works on github after we merge it though because only then can we actually run it here.
=> Add automated deployment script that runs on push to branches

.pre-commit-config.yaml, cpmonitor/static/css/_lz-body.scss, cpmonitor/static/css/_lz-footer.scss, cpmonitor/static/css/_lz-global.scss, cpmonitor/static/css/_lz-header.scss, cpmonitor/static/css/_lz-menu.scss, cpmonitor/static/css/_lz-variables.scss, cpmonitor/static/css/localzero.css, cpmonitor/static/css/localzero.scss, cpmonitor/static/css/main.css, cpmonitor/static/css/main.scss, cpmonitor/static/js/localzero.js, cpmonitor/static/js/main.js, package.json, yarn.lock
Adds prettier with a pre-commit hook. It formats css, scss, and javascript files. I left the formatting options mostly to their default values.
=> [#81] Add prettier

.github/workflows/deploy.yml, deploy.sh
Fixes deployment failing because git username/mail are not configured, as described here: https://github.com/GermanZero-de/klimaschutzmonitor/issues/21#issuecomment-1745000927
I tested the fix locally using [act](https://github.com/nektos/act).
=> [#21] Configure missing git identity

cpmonitor/urls.py
I could not reproduce this locally which I find confusing.
But my theory is that Martor calls the imgur uploader instead of our uploader because the url is added before ours.
=> [#381] try to fix the martor image upload

cpmonitor/serializers.py, cpmonitor/urls.py, cpmonitor/views.py
As discussed in the stand up today we need a temporary quick fix: two new endpoints which are returning only cities and tasks which are not in draft mode:
- api/cities-without-drafts
- api/cities/<str:slug>/tasks-without-drafts
=> [#493] Add endpoints for cities and tasks which are not in draft mode

deploy.sh
Removes two debug statements that lead to errors. See commit a83c8a4b4291289e4edf18250bfdaac85f1e3ce2 for the additional line that should have fixed the original issue.
=> [#628] Remove failing debug command from deploy script

frontend/app/globals.scss
There was only one space missing in the font name in order for it to be correctly recognized (PTSerif vs PT Serif).
**Before**
**Now**
=> fix(fonts): add space to PT Serif to make font naming correct

frontend/app/(dashboard)/[city]/massnahmen/[...task]/page.tsx
As described in the ticket, there was a doubling of information concerning the supporting ngos. As suggested, the ngo name was removed from the content, since it's present inside the left sidebar already.
| Before | Now |
|--------|--------|
| <img width="1060" alt="image" src="https://github.com/user-attachments/assets/7c039768-9f1c-4631-9689-0d2ae9219150" /> | <img width="1042" alt="image" src="https://github.com/user-attachments/assets/62e9bfbe-a7d4-4d9c-a271-cc8de5eeb8d0" /> |
=> refactor(massnahmen): remove double display of supporting ngos

docker-compose.yml
The nginx instances for testing and production are reachable via their respective docker networks testing_nginx_network and production_nginx_network, and the reverse-proxy composition, which shares these networks.
=> Don't expose container ports unnecessarily

frontend/app/(pages)/projektbeschreibung/page.tsx, frontend/app/components/Header.tsx
As desired in the ticket, the Topmaßnahmen nav item is now an external link.
I additionally turned the first menu item from a dropdown into 2 items since the hierarchy seemed over-engineered and we had 3 items linking to the same page ("Monitoring", "Alle Kommunen" AND the logo itself).
| Was | Is Now |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/5ca25079-5288-4d4c-9cbd-a5730c37cbb4) | <img width="1181" alt="image" src="https://github.com/user-attachments/assets/faa79117-8ffd-42de-a5d9-266bd6392917" /> |
=> refactor(header): turn topmassnahmen into external link and make first nav item flat
